<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="_Core\Resources\Images\Englich.jpg" />
    <None Remove="_Core\Resources\Images\German.jpg" />
    <None Remove="_Core\Resources\Images\ProfilePhoto.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProMedScope.Controls\ProMedScope.Controls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="_Core\Resources\Images\Englich.jpg" />
    <Resource Include="_Core\Resources\Images\German.jpg" />
    <Resource Include="_Core\Resources\Images\ProfilePhoto.png" />
    <Resource Include="_Core\Resources\Images\TitleBarLogo.png" />
  </ItemGroup>

</Project>
